export const SUCCESS = 'SUCCESS'
export const SHOW_MODAL = 'SHOW_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const CHECK_AND_ADD_TO_CART = 'CHECK_AND_ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const DELETE_FROM_CART = 'DELETE_FROM_CART'
export const INCREASE_COUNT = 'INCREASE_COUNT'
export const DECREASE_COUNT = 'DECREASE_COUNT'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';


